export type Movie = {
  id: number;
  title: string;
  vote_average?: number;
  vote_count?: number;
  status?: string;
  release_date?: string;
  revenue?: number;
  runtime?: number;
  adult?: string;
  backdrop_path?: string;
  budget?: number;
  homepage?: string;
  imdb_id?: string;
  original_language?: string;
  original_title?: string;
  overview?: string;
  popularity?: number;
  poster_path?: string;
  tagline?: string;
  genres?: string;
  production_companies?: string;
  production_countries?: string;
  spoken_languages?: string;
  keywords?: string;
};
